site_name: Guia Hackintosh Brasil
site_author: Gilberto | Dev
site_description: O guia definitivo para hardware compat√≠vel no mercado brasileiro.

theme:
  name: material
  language: pt-BR  # Define a interface do site em portugu√™s
  palette:
    # Op√ß√£o de Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Op√ß√£o de Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  
  features:
    - navigation.tabs        # Menu horizontal no topo
    - navigation.sections    # Organiza melhor a barra lateral
    - navigation.top         # Bot√£o "voltar ao topo"
    - search.suggest         # Sugest√µes autom√°ticas na busca
    - search.highlight       # Destaca o texto encontrado

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Gilberto-Mascena
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gilberto-mascena-dev     
    - icon: fontawesome/solid/paper-plane
      link: mailto:gilbertomascena@gmail.com

copyright: >
  Copyright &copy; 2026 Gilberto Mascena. <br>
  Este guia √© um projeto independente. Apple e macOS s√£o marcas registradas da Apple Inc.

# Adiciona suporte a blocos de notas, avisos e √≠cones no texto
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji: # Adicione isso para habilitar os √≠cones
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - In√≠cio: index.md
  - üõí Guia de Compras: compras.md
  - ‚ùì Perguntas Frequentes: faq.md
  - ‚öñÔ∏è Licen√ßa: licenca.md