site_name: Guia Hackintosh Brasil
site_author: Gilberto | Dev
site_description: O guia definitivo para hardware compat√≠vel no mercado brasileiro.

theme:
  name: material
  language: pt-BR  # Define a interface do site em portugu√™s
  palette:
    # Op√ß√£o de Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Op√ß√£o de Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  
  features:
    - navigation.tabs        # Menu horizontal no topo
    - navigation.sections    # Organiza melhor a barra lateral
    - navigation.top         # Bot√£o "voltar ao topo"
    - search.suggest         # Sugest√µes autom√°ticas na busca
    - search.highlight       # Destaca o texto encontrado

# Adiciona suporte a blocos de notas, avisos e √≠cones no texto
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - In√≠cio: index.md
  - üõí Guia de Compras: compras.md
  - ‚ùì Perguntas Frequentes: faq.md